[package]
name = "mass_networking"
version = "0.2.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 2

[dependencies]
bevy = "0.12"
bevy_ggrs = { version = "0.14", features = ["wasm-bindgen"] }
bevy_matchbox = { version = "0.8", features = ["ggrs"] }
bevy_roll_safe = "0.1"
clap = { version = "4.4", features = ["derive"] }
